### PR TITLE
REF: update transfocator class to support new PLC/IOC

### PR DESCRIPTION
**Pull request by klauer**
Related:
https://github.com/pcdshub/lcls-plc-mfx-be-lens-interlock/pull/7
https://github.com/pcdshub/ioc-mfx-tfs-lens/pull/1

### CODE REVIEW

**Comment by klauer** [comment]
Energy sweep is looking like this with black 'x' marking trips:
image

Not ideal - it's scanning a bit faster than the modbus-based responses can be retrieved. May have to add in some delays to remove or reduce that effect, then perhaps I can bring back in a line plot instead of a scatter for the "no-go" regions.

Also should pick some sensible lens combinations to make a more full sweep.

**Comment by klauer** [comment]
Getting closer:
image

**Comment by klauer** [comment]
Now 99% what I expect, but some outliers that confuse me:
image

**Review by ZLLentz — APPROVED** [review]
I don't have much to say here, it looks solid. No red flags, but I also have no real understanding of what is being accomplished in the PLC/IOC changes.

**Comment by klauer** [comment]
A fair review, indeed. Thanks @ZLLentz 👍

**Pull request merged**
